### ISSUE TITLE
Add supabase auth as separated middleware to be imported into pages

### ISSUE THREAD

**Issue by y-neck** [y-neck/opus#12]
https://github.com/y-neck/opus/blob/57e955a714e2c3189a34187b56f58041648d278a/pages/task-overview.vue#L41-L47

**Comment by kevinschaerer** [comment]
Middleware added to project. Please add the following code into the pages which should be protected.

```
// Page Meta
definePageMeta({
middleware: 'auth'
});
```

**Comment by y-neck** [comment]
Fixed by https://github.com/y-neck/opus/commit/9a1d56bbd66666096ac7bb42d90933bb6e3511a6
